language: php

php:
  - "7.2"
  - "7.1"
  - "7.0"
  - nightly

allow_failures:
  -php: nightly

sudo: false

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer install --prefer-source --no-interaction --no-progress
